name: Drive orqali AAB dan APK yasash

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  convert:
    runs-on: ubuntu-latest

    steps:
      - name: Java o'rnatish
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '17'

      - name: Bundletool yuklash
        run: wget https://github.com/google/bundletool/releases/download/1.17.0/bundletool-all-1.17.0.jar -O bundletool.jar

      - name: Maxsus yuklovchini o'rnatish
        run: pip install gdown

      - name: AAB faylni Drive'dan tortib olish
        run: gdown "1D8E8eY8ZjM-qE_ZZC_R9c570COx2RfWN" -O my_app.aab

      - name: APK yaratish
        run: |
          java -jar bundletool.jar build-apks \
            --bundle="my_app.aab" \
            --output="my_app.apks" \
            --mode=universal

      - name: APK ni ajratib olish
        run: |
          unzip my_app.apks -d apks_dir
          mv apks_dir/universal.apk ./Tayyor-APK.apk

      - name: APK ni yuklab olishga tayyorlash
        uses: actions/upload-artifact@v4
        with:
          name: Mening-APK-Faylim
          path: Tayyor-APK.apk
          
